meta_product_name: "Habitracker"
meta_title: "Habitracker - Reach for the stars"
meta_description: "Helping you to keep track of your habits"
meta_image: "colours.jpg" # should exist in `app/assets/images/`
